/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.CalculoM1;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Michael
 */
public class VentanaKirchhoff extends javax.swing.JFrame{

    /**
     * Creates new form VentanaKirchhoff
     */
    public VentanaKirchhoff() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbM1RV1 = new javax.swing.JComboBox<>();
        txtM1RV1 = new javax.swing.JTextField();
        cmbM1RV2 = new javax.swing.JComboBox<>();
        txtM1RV2 = new javax.swing.JTextField();
        cmbM1RV3 = new javax.swing.JComboBox<>();
        txtM1RV3 = new javax.swing.JTextField();
        cmbM1V1 = new javax.swing.JComboBox<>();
        txtM1V1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblM1Res2 = new javax.swing.JLabel();
        lblM1Res1 = new javax.swing.JLabel();
        lblM1Res3 = new javax.swing.JLabel();
        lblM1R2 = new javax.swing.JLabel();
        lblM1R1 = new javax.swing.JLabel();
        lblM1R3 = new javax.swing.JLabel();
        lblVAlM1R1 = new javax.swing.JLabel();
        lblVAlM1R2 = new javax.swing.JLabel();
        lblVAlM1R3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnM1Result = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmbM2RV1 = new javax.swing.JComboBox<>();
        txtM2RV1 = new javax.swing.JTextField();
        cmbM2RV2 = new javax.swing.JComboBox<>();
        txtM2RV2 = new javax.swing.JTextField();
        cmbM2RV3 = new javax.swing.JComboBox<>();
        txtM2RV3 = new javax.swing.JTextField();
        cmbM2RV4 = new javax.swing.JComboBox<>();
        txtM2RV4 = new javax.swing.JTextField();
        cmbM2RV5 = new javax.swing.JComboBox<>();
        txtM2RV5 = new javax.swing.JTextField();
        cmbM2RV6 = new javax.swing.JComboBox<>();
        txtM2RV6 = new javax.swing.JTextField();
        cmbM2V1 = new javax.swing.JComboBox<>();
        txtM2V1 = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblM2Res4 = new javax.swing.JLabel();
        lblM2Res3 = new javax.swing.JLabel();
        lblM2Res6 = new javax.swing.JLabel();
        lblM2Res1 = new javax.swing.JLabel();
        lblM2Res2 = new javax.swing.JLabel();
        lblM2Res5 = new javax.swing.JLabel();
        DosMalla = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cmbM3RV1 = new javax.swing.JComboBox<>();
        txtM3RV1 = new javax.swing.JTextField();
        cmbM3RV2 = new javax.swing.JComboBox<>();
        txtM3RV2 = new javax.swing.JTextField();
        cmbM3RV3 = new javax.swing.JComboBox<>();
        txtM3RV3 = new javax.swing.JTextField();
        cmbM3RV4 = new javax.swing.JComboBox<>();
        txtM3RV4 = new javax.swing.JTextField();
        cmbM3RV5 = new javax.swing.JComboBox<>();
        txtM3RV5 = new javax.swing.JTextField();
        cmbM3RV6 = new javax.swing.JComboBox<>();
        txtM3RV6 = new javax.swing.JTextField();
        cmbM3RV7 = new javax.swing.JComboBox<>();
        txtM3RV7 = new javax.swing.JTextField();
        cmbM3RV8 = new javax.swing.JComboBox<>();
        txtM3RV8 = new javax.swing.JTextField();
        cmbM3RV9 = new javax.swing.JComboBox<>();
        txtM3RV9 = new javax.swing.JTextField();
        cmbM3V1 = new javax.swing.JComboBox<>();
        txtM3V1 = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lblM3Res1 = new javax.swing.JLabel();
        lblM3Res4 = new javax.swing.JLabel();
        lblM3Res7 = new javax.swing.JLabel();
        lblM3Res3 = new javax.swing.JLabel();
        lblM3Res6 = new javax.swing.JLabel();
        lblM3Res9 = new javax.swing.JLabel();
        lblM3Res8 = new javax.swing.JLabel();
        lblM3Res2 = new javax.swing.JLabel();
        lblM3Res5 = new javax.swing.JLabel();
        TresMalla = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Ley de Kirchhoff");
        setAlwaysOnTop(true);
        setSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Ley de Kirchhoff - Una Malla- ");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbM1RV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM1RV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R1", "None" }));

        txtM1RV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM1RV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM1RV1ActionPerformed(evt);
            }
        });

        cmbM1RV2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM1RV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R2", "None" }));
        cmbM1RV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbM1RV2ActionPerformed(evt);
            }
        });

        txtM1RV2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM1RV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM1RV2ActionPerformed(evt);
            }
        });

        cmbM1RV3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM1RV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R3", "None" }));

        txtM1RV3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbM1V1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM1V1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V" }));

        txtM1V1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbM1V1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(txtM1V1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbM1RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtM1RV3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbM1RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtM1RV2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbM1RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtM1RV1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM1RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM1RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM1RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM1RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM1RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM1RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM1V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM1V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblM1Res2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resV.png"))); // NOI18N
        jLayeredPane1.add(lblM1Res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 30, 80));

        lblM1Res1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane1.add(lblM1Res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        lblM1Res3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane1.add(lblM1Res3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, 40));

        lblM1R2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblM1R2.setText("R2");
        jLayeredPane1.add(lblM1R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        lblM1R1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblM1R1.setText("R1");
        jLayeredPane1.add(lblM1R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        lblM1R3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblM1R3.setText("R3");
        jLayeredPane1.add(lblM1R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        jLayeredPane1.add(lblVAlM1R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 40, 20));
        jLayeredPane1.add(lblVAlM1R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 40, 20));
        jLayeredPane1.add(lblVAlM1R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/una malla.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        btnM1Result.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnM1Result.setText("Resultado");
        btnM1Result.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnM1Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM1ResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnM1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnM1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Una malla", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Ley de Kirchhoff - Dos Malla- ");

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbM2RV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2RV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R1", "None" }));

        txtM2RV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM2RV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2RV1ActionPerformed(evt);
            }
        });

        cmbM2RV2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2RV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R2", "None" }));

        txtM2RV2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM2RV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2RV2ActionPerformed(evt);
            }
        });

        cmbM2RV3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2RV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R3", "None" }));

        txtM2RV3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbM2RV4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2RV4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R4", "None" }));

        txtM2RV4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM2RV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2RV4ActionPerformed(evt);
            }
        });

        cmbM2RV5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2RV5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V2", "None" }));
        cmbM2RV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbM2RV5ActionPerformed(evt);
            }
        });

        txtM2RV5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM2RV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2RV5ActionPerformed(evt);
            }
        });

        cmbM2RV6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2RV6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R6", "None" }));

        txtM2RV6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbM2V1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM2V1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V1" }));

        txtM2V1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbM2RV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM2RV4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbM2RV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM2RV5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbM2RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM2RV1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbM2RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM2RV2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbM2RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM2RV3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbM2V1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbM2RV6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtM2RV6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtM2V1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2RV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2RV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2RV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2RV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2RV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2RV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM2V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM2V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblM2Res4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane2.add(lblM2Res4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 40));

        lblM2Res3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane2.add(lblM2Res3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 30));

        lblM2Res6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane2.add(lblM2Res6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        lblM2Res1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane2.add(lblM2Res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        lblM2Res2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resV.png"))); // NOI18N
        jLayeredPane2.add(lblM2Res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 30, 80));

        lblM2Res5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bat.png"))); // NOI18N
        jLayeredPane2.add(lblM2Res5, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 160, -1, 40));

        DosMalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dos mallas.png"))); // NOI18N
        jLayeredPane2.add(DosMalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        DosMalla.getAccessibleContext().setAccessibleParent(jPanel3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dos mallas", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Ley de Kirchhoff - Tres Malla- ");

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbM3RV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R1", "None" }));
        cmbM3RV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbM3RV1ActionPerformed(evt);
            }
        });

        txtM3RV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3RV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3RV1ActionPerformed(evt);
            }
        });

        cmbM3RV2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R2", "None" }));

        txtM3RV2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3RV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3RV2ActionPerformed(evt);
            }
        });

        cmbM3RV3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R3", "None" }));

        txtM3RV3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbM3RV4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R4", "None" }));

        txtM3RV4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3RV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3RV4ActionPerformed(evt);
            }
        });

        cmbM3RV5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R5", "None" }));

        txtM3RV5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3RV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3RV5ActionPerformed(evt);
            }
        });

        cmbM3RV6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R6", "None" }));

        txtM3RV6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbM3RV7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R7", "None" }));

        txtM3RV7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3RV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3RV7ActionPerformed(evt);
            }
        });

        cmbM3RV8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V2", "None" }));

        txtM3RV8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3RV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM3RV8ActionPerformed(evt);
            }
        });

        cmbM3RV9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3RV9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R9", "None" }));

        txtM3RV9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbM3V1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbM3V1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V1" }));

        txtM3V1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbM3RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtM3RV3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbM3RV9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbM3V1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM3V1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtM3RV9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3RV9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3RV9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbM3V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtM3V1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblM3Res1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblM3Res4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        lblM3Res7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        lblM3Res3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        lblM3Res6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        lblM3Res9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resH.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        lblM3Res8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bat.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 50, 40));

        lblM3Res2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resV.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 30, 80));

        lblM3Res5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resV.png"))); // NOI18N
        jLayeredPane3.add(lblM3Res5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 30, 80));

        TresMalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tres mallas.png"))); // NOI18N
        jLayeredPane3.add(TresMalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        TresMalla.getAccessibleContext().setAccessibleDescription("");

        jLabel5.setText("jLabel5");
        jLayeredPane3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(97, 97, 97)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tres mallas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblM1R1() {
        return lblM1R1;
    }

    public void setLblM1R1(JLabel lblM1R1) {
        this.lblM1R1 = lblM1R1;
    }

    public JLabel getLblVAlM1R1() {
        return lblVAlM1R1;
    }

    public void setLblVAlM1R1(JLabel lblVAlM1R1) {
        this.lblVAlM1R1 = lblVAlM1R1;
    }

    public JLabel getLblVAlM1R2() {
        return lblVAlM1R2;
    }

    public void setLblVAlM1R2(JLabel lblVAlM1R2) {
        this.lblVAlM1R2 = lblVAlM1R2;
    }

    public JLabel getLblVAlM1R3() {
        return lblVAlM1R3;
    }

    public void setLblVAlM1R3(JLabel lblVAlM1R3) {
        this.lblVAlM1R3 = lblVAlM1R3;
    }

    public JLabel getLblM1R2() {
        return lblM1R2;
    }

    public void setLblM1R2(JLabel lblM1R2) {
        this.lblM1R2 = lblM1R2;
    }

    public JLabel getLblM1R3() {
        return lblM1R3;
    }

    public void setLblM1R3(JLabel lblM1R3) {
        this.lblM1R3 = lblM1R3;
    }

    private void txtM1RV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM1RV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM1RV2ActionPerformed

    private void txtM1RV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM1RV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM1RV1ActionPerformed

    private void txtM2RV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2RV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2RV1ActionPerformed

    private void txtM2RV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2RV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2RV2ActionPerformed

    private void txtM2RV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2RV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2RV4ActionPerformed

    private void txtM2RV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2RV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2RV5ActionPerformed

    private void txtM3RV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3RV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3RV1ActionPerformed

    private void txtM3RV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3RV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3RV2ActionPerformed

    private void txtM3RV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3RV4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3RV4ActionPerformed

    private void txtM3RV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3RV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3RV5ActionPerformed

    private void txtM3RV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3RV7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3RV7ActionPerformed

    private void txtM3RV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM3RV8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3RV8ActionPerformed

    private void cmbM3RV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbM3RV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbM3RV1ActionPerformed

    private void cmbM2RV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbM2RV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbM2RV5ActionPerformed

    private void cmbM1RV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbM1RV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbM1RV2ActionPerformed

    private void btnM1ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM1ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnM1ResultActionPerformed

    public JButton getBtnM1Result() {
        return btnM1Result;
    }

    public void setBtnM1Result(JButton btnM1Result) {
        this.btnM1Result = btnM1Result;
    }

    public JComboBox<String> getCmbM1V1() {
        return cmbM1V1;
    }

    public void setCmbM1V1(JComboBox<String> cmbM1V1) {
        this.cmbM1V1 = cmbM1V1;
    }

    public JComboBox<String> getCmbM2V1() {
        return cmbM2V1;
    }

    public void setCmbM2V1(JComboBox<String> cmbM2V1) {
        this.cmbM2V1 = cmbM2V1;
    }

    public JComboBox<String> getCmbM3V1() {
        return cmbM3V1;
    }

    public void setCmbM3V1(JComboBox<String> cmbM3V1) {
        this.cmbM3V1 = cmbM3V1;
    }

    public JTextField getTxtM1V1() {
        return txtM1V1;
    }

    public void setTxtM1V1(JTextField txtM1V1) {
        this.txtM1V1 = txtM1V1;
    }

    public JTextField getTxtM2V1() {
        return txtM2V1;
    }

    public void setTxtM2V1(JTextField txtM2V1) {
        this.txtM2V1 = txtM2V1;
    }

    public JTextField getTxtM3V1() {
        return txtM3V1;
    }

    public void setTxtM3V1(JTextField txtM3V1) {
        this.txtM3V1 = txtM3V1;
    }

    public JLabel getLblResV() {
        return lblM1Res2;
    }

    public void setLblResV(JLabel lblResV) {
        this.lblM1Res2 = lblResV;
    }

    public JLabel getDosMalla() {
        return DosMalla;
    }

    public void setDosMalla(JLabel DosMalla) {
        this.DosMalla = DosMalla;
    }

    public JComboBox<String> getCmbM1RV1() {
        return cmbM1RV1;
    }

    public void setCmbM1RV1(JComboBox<String> cmbM1RV1) {
        this.cmbM1RV1 = cmbM1RV1;
    }

    public JComboBox<String> getCmbM1RV2() {
        return cmbM1RV2;
    }

    public void setCmbM1RV2(JComboBox<String> cmbM1RV2) {
        this.cmbM1RV2 = cmbM1RV2;
    }

    public JComboBox<String> getCmbM1RV3() {
        return cmbM1RV3;
    }

    public void setCmbM1RV3(JComboBox<String> cmbM1RV3) {
        this.cmbM1RV3 = cmbM1RV3;
    }

    public JComboBox<String> getCmbM2RV1() {
        return cmbM2RV1;
    }

    public void setCmbM2RV1(JComboBox<String> cmbM2RV1) {
        this.cmbM2RV1 = cmbM2RV1;
    }

    public JComboBox<String> getCmbM2RV2() {
        return cmbM2RV2;
    }

    public void setCmbM2RV2(JComboBox<String> cmbM2RV2) {
        this.cmbM2RV2 = cmbM2RV2;
    }

    public JComboBox<String> getCmbM2RV3() {
        return cmbM2RV3;
    }

    public void setCmbM2RV3(JComboBox<String> cmbM2RV3) {
        this.cmbM2RV3 = cmbM2RV3;
    }

    public JComboBox<String> getCmbM2RV4() {
        return cmbM2RV4;
    }

    public void setCmbM2RV4(JComboBox<String> cmbM2RV4) {
        this.cmbM2RV4 = cmbM2RV4;
    }

    public JComboBox<String> getCmbM2RV5() {
        return cmbM2RV5;
    }

    public void setCmbM2RV5(JComboBox<String> cmbM2RV5) {
        this.cmbM2RV5 = cmbM2RV5;
    }

    public JComboBox<String> getCmbM2RV6() {
        return cmbM2RV6;
    }

    public void setCmbM2RV6(JComboBox<String> cmbM2RV6) {
        this.cmbM2RV6 = cmbM2RV6;
    }

    public JComboBox<String> getCmbM3RV1() {
        return cmbM3RV1;
    }

    public void setCmbM3RV1(JComboBox<String> cmbM3RV1) {
        this.cmbM3RV1 = cmbM3RV1;
    }

    public JComboBox<String> getCmbM3RV2() {
        return cmbM3RV2;
    }

    public void setCmbM3RV2(JComboBox<String> cmbM3RV2) {
        this.cmbM3RV2 = cmbM3RV2;
    }

    public JComboBox<String> getCmbM3RV3() {
        return cmbM3RV3;
    }

    public void setCmbM3RV3(JComboBox<String> cmbM3RV3) {
        this.cmbM3RV3 = cmbM3RV3;
    }

    public JComboBox<String> getCmbM3RV4() {
        return cmbM3RV4;
    }

    public void setCmbM3RV4(JComboBox<String> cmbM3RV4) {
        this.cmbM3RV4 = cmbM3RV4;
    }

    public JComboBox<String> getCmbM3RV5() {
        return cmbM3RV5;
    }

    public void setCmbM3RV5(JComboBox<String> cmbM3RV5) {
        this.cmbM3RV5 = cmbM3RV5;
    }

    public JComboBox<String> getCmbM3RV6() {
        return cmbM3RV6;
    }

    public void setCmbM3RV6(JComboBox<String> cmbM3RV6) {
        this.cmbM3RV6 = cmbM3RV6;
    }

    public JComboBox<String> getCmbM3RV7() {
        return cmbM3RV7;
    }

    public void setCmbM3RV7(JComboBox<String> cmbM3RV7) {
        this.cmbM3RV7 = cmbM3RV7;
    }

    public JComboBox<String> getCmbM3RV8() {
        return cmbM3RV8;
    }

    public void setCmbM3RV8(JComboBox<String> cmbM3RV8) {
        this.cmbM3RV8 = cmbM3RV8;
    }

    public JComboBox<String> getCmbM3RV9() {
        return cmbM3RV9;
    }

    public void setCmbM3RV9(JComboBox<String> cmbM3RV9) {
        this.cmbM3RV9 = cmbM3RV9;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return TresMalla;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.TresMalla = jLabel5;
    }

    public JLabel getjLabel6() {
        return lblM1Res2;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.lblM1Res2 = jLabel6;
    }

    public JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    public void setjLayeredPane1(JLayeredPane jLayeredPane1) {
        this.jLayeredPane1 = jLayeredPane1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JLabel getTresMalla() {
        return TresMalla;
    }

    public void setTresMalla(JLabel TresMalla) {
        this.TresMalla = TresMalla;
    }

    public JLayeredPane getjLayeredPane3() {
        return jLayeredPane3;
    }

    public void setjLayeredPane3(JLayeredPane jLayeredPane3) {
        this.jLayeredPane3 = jLayeredPane3;
    }

    public JLabel getLblM3Res1() {
        return lblM3Res1;
    }

    public void setLblM3Res1(JLabel lblM3Res1) {
        this.lblM3Res1 = lblM3Res1;
    }

    public JLabel getLblM3Res2() {
        return lblM3Res2;
    }

    public void setLblM3Res2(JLabel lblM3Res2) {
        this.lblM3Res2 = lblM3Res2;
    }

    public JLabel getLblM3Res3() {
        return lblM3Res3;
    }

    public void setLblM3Res3(JLabel lblM3Res3) {
        this.lblM3Res3 = lblM3Res3;
    }

    public JLabel getLblM3Res4() {
        return lblM3Res4;
    }

    public void setLblM3Res4(JLabel lblM3Res4) {
        this.lblM3Res4 = lblM3Res4;
    }

    public JLabel getLblM3Res5() {
        return lblM3Res5;
    }

    public void setLblM3Res5(JLabel lblM3Res5) {
        this.lblM3Res5 = lblM3Res5;
    }

    public JLabel getLblM3Res6() {
        return lblM3Res6;
    }

    public void setLblM3Res6(JLabel lblM3Res6) {
        this.lblM3Res6 = lblM3Res6;
    }

    public JLabel getLblM3Res7() {
        return lblM3Res7;
    }

    public void setLblM3Res7(JLabel lblM3Res7) {
        this.lblM3Res7 = lblM3Res7;
    }

    public JLabel getLblM3Res8() {
        return lblM3Res8;
    }

    public void setLblM3Res8(JLabel lblM3Res8) {
        this.lblM3Res8 = lblM3Res8;
    }

    public JLabel getLblM3Res9() {
        return lblM3Res9;
    }

    public void setLblM3Res9(JLabel lblM3Res9) {
        this.lblM3Res9 = lblM3Res9;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JLayeredPane getjLayeredPane2() {
        return jLayeredPane2;
    }

    public void setjLayeredPane2(JLayeredPane jLayeredPane2) {
        this.jLayeredPane2 = jLayeredPane2;
    }

    public JLabel getLblM2Res1() {
        return lblM2Res1;
    }

    public void setLblM2Res1(JLabel lblM2Res1) {
        this.lblM2Res1 = lblM2Res1;
    }

    public JLabel getLblM2Res2() {
        return lblM2Res2;
    }

    public void setLblM2Res2(JLabel lblM2Res2) {
        this.lblM2Res2 = lblM2Res2;
    }

    public JLabel getLblM2Res3() {
        return lblM2Res3;
    }

    public void setLblM2Res3(JLabel lblM2Res3) {
        this.lblM2Res3 = lblM2Res3;
    }

    public JLabel getLblM2Res4() {
        return lblM2Res4;
    }

    public void setLblM2Res4(JLabel lblM2Res4) {
        this.lblM2Res4 = lblM2Res4;
    }

    public JLabel getLblM2Res5() {
        return lblM2Res5;
    }

    public void setLblM2Res5(JLabel lblM2Res5) {
        this.lblM2Res5 = lblM2Res5;
    }

    public JLabel getLblM2Res6() {
        return lblM2Res6;
    }

    public void setLblM2Res6(JLabel lblM2Res6) {
        this.lblM2Res6 = lblM2Res6;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public void setjPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTextField getTxtM1RV1() {
        return txtM1RV1;
    }

    public void setTxtM1RV1(JTextField txtM1RV1) {
        this.txtM1RV1 = txtM1RV1;
    }

    public JTextField getTxtM1RV2() {
        return txtM1RV2;
    }

    public void setTxtM1RV2(JTextField txtM1RV2) {
        this.txtM1RV2 = txtM1RV2;
    }

    public JTextField getTxtM1RV3() {
        return txtM1RV3;
    }

    public void setTxtM1RV3(JTextField txtM1RV3) {
        this.txtM1RV3 = txtM1RV3;
    }

    public JTextField getTxtM2RV1() {
        return txtM2RV1;
    }

    public void setTxtM2RV1(JTextField txtM2RV1) {
        this.txtM2RV1 = txtM2RV1;
    }

    public JTextField getTxtM2RV2() {
        return txtM2RV2;
    }

    public void setTxtM2RV2(JTextField txtM2RV2) {
        this.txtM2RV2 = txtM2RV2;
    }

    public JTextField getTxtM2RV3() {
        return txtM2RV3;
    }

    public void setTxtM2RV3(JTextField txtM2RV3) {
        this.txtM2RV3 = txtM2RV3;
    }

    public JTextField getTxtM2RV4() {
        return txtM2RV4;
    }

    public void setTxtM2RV4(JTextField txtM2RV4) {
        this.txtM2RV4 = txtM2RV4;
    }

    public JTextField getTxtM2RV5() {
        return txtM2RV5;
    }

    public void setTxtM2RV5(JTextField txtM2RV5) {
        this.txtM2RV5 = txtM2RV5;
    }

    public JTextField getTxtM2RV6() {
        return txtM2RV6;
    }

    public void setTxtM2RV6(JTextField txtM2RV6) {
        this.txtM2RV6 = txtM2RV6;
    }

    public JTextField getTxtM3RV1() {
        return txtM3RV1;
    }

    public void setTxtM3RV1(JTextField txtM3RV1) {
        this.txtM3RV1 = txtM3RV1;
    }

    public JTextField getTxtM3RV2() {
        return txtM3RV2;
    }

    public void setTxtM3RV2(JTextField txtM3RV2) {
        this.txtM3RV2 = txtM3RV2;
    }

    public JTextField getTxtM3RV3() {
        return txtM3RV3;
    }

    public void setTxtM3RV3(JTextField txtM3RV3) {
        this.txtM3RV3 = txtM3RV3;
    }

    public JTextField getTxtM3RV4() {
        return txtM3RV4;
    }

    public void setTxtM3RV4(JTextField txtM3RV4) {
        this.txtM3RV4 = txtM3RV4;
    }

    public JTextField getTxtM3RV5() {
        return txtM3RV5;
    }

    public void setTxtM3RV5(JTextField txtM3RV5) {
        this.txtM3RV5 = txtM3RV5;
    }

    public JTextField getTxtM3RV6() {
        return txtM3RV6;
    }

    public void setTxtM3RV6(JTextField txtM3RV6) {
        this.txtM3RV6 = txtM3RV6;
    }

    public JTextField getTxtM3RV7() {
        return txtM3RV7;
    }

    public JLabel getLblM1Res1() {
        return lblM1Res1;
    }

    public void setLblM1Res1(JLabel lblM1Res1) {
        this.lblM1Res1 = lblM1Res1;
    }

    public JLabel getLblM1Res2() {
        return lblM1Res2;
    }

    public void setLblM1Res2(JLabel lblM1Res2) {
        this.lblM1Res2 = lblM1Res2;
    }

    public JLabel getLblM1Res3() {
        return lblM1Res3;
    }

    public void setLblM1Res3(JLabel lblM1Res3) {
        this.lblM1Res3 = lblM1Res3;
    }

    public void setTxtM3RV7(JTextField txtM3RV7) {
        this.txtM3RV7 = txtM3RV7;
    }

    public JTextField getTxtM3RV8() {
        return txtM3RV8;
    }

    public void setTxtM3RV8(JTextField txtM3RV8) {
        this.txtM3RV8 = txtM3RV8;
    }

    public JTextField getTxtM3RV9() {
        return txtM3RV9;
    }

    public void setTxtM3RV9(JTextField txtM3RV9) {
        this.txtM3RV9 = txtM3RV9;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaKirchhoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaKirchhoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaKirchhoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaKirchhoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaKirchhoff().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DosMalla;
    private javax.swing.JLabel TresMalla;
    private javax.swing.JButton btnM1Result;
    private javax.swing.JComboBox<String> cmbM1RV1;
    private javax.swing.JComboBox<String> cmbM1RV2;
    private javax.swing.JComboBox<String> cmbM1RV3;
    private javax.swing.JComboBox<String> cmbM1V1;
    private javax.swing.JComboBox<String> cmbM2RV1;
    private javax.swing.JComboBox<String> cmbM2RV2;
    private javax.swing.JComboBox<String> cmbM2RV3;
    private javax.swing.JComboBox<String> cmbM2RV4;
    private javax.swing.JComboBox<String> cmbM2RV5;
    private javax.swing.JComboBox<String> cmbM2RV6;
    private javax.swing.JComboBox<String> cmbM2V1;
    private javax.swing.JComboBox<String> cmbM3RV1;
    private javax.swing.JComboBox<String> cmbM3RV2;
    private javax.swing.JComboBox<String> cmbM3RV3;
    private javax.swing.JComboBox<String> cmbM3RV4;
    private javax.swing.JComboBox<String> cmbM3RV5;
    private javax.swing.JComboBox<String> cmbM3RV6;
    private javax.swing.JComboBox<String> cmbM3RV7;
    private javax.swing.JComboBox<String> cmbM3RV8;
    private javax.swing.JComboBox<String> cmbM3RV9;
    private javax.swing.JComboBox<String> cmbM3V1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblM1R1;
    private javax.swing.JLabel lblM1R2;
    private javax.swing.JLabel lblM1R3;
    private javax.swing.JLabel lblM1Res1;
    private javax.swing.JLabel lblM1Res2;
    private javax.swing.JLabel lblM1Res3;
    private javax.swing.JLabel lblM2Res1;
    private javax.swing.JLabel lblM2Res2;
    private javax.swing.JLabel lblM2Res3;
    private javax.swing.JLabel lblM2Res4;
    private javax.swing.JLabel lblM2Res5;
    private javax.swing.JLabel lblM2Res6;
    private javax.swing.JLabel lblM3Res1;
    private javax.swing.JLabel lblM3Res2;
    private javax.swing.JLabel lblM3Res3;
    private javax.swing.JLabel lblM3Res4;
    private javax.swing.JLabel lblM3Res5;
    private javax.swing.JLabel lblM3Res6;
    private javax.swing.JLabel lblM3Res7;
    private javax.swing.JLabel lblM3Res8;
    private javax.swing.JLabel lblM3Res9;
    private javax.swing.JLabel lblVAlM1R1;
    private javax.swing.JLabel lblVAlM1R2;
    private javax.swing.JLabel lblVAlM1R3;
    private javax.swing.JTextField txtM1RV1;
    private javax.swing.JTextField txtM1RV2;
    private javax.swing.JTextField txtM1RV3;
    private javax.swing.JTextField txtM1V1;
    private javax.swing.JTextField txtM2RV1;
    private javax.swing.JTextField txtM2RV2;
    private javax.swing.JTextField txtM2RV3;
    private javax.swing.JTextField txtM2RV4;
    private javax.swing.JTextField txtM2RV5;
    private javax.swing.JTextField txtM2RV6;
    private javax.swing.JTextField txtM2V1;
    private javax.swing.JTextField txtM3RV1;
    private javax.swing.JTextField txtM3RV2;
    private javax.swing.JTextField txtM3RV3;
    private javax.swing.JTextField txtM3RV4;
    private javax.swing.JTextField txtM3RV5;
    private javax.swing.JTextField txtM3RV6;
    private javax.swing.JTextField txtM3RV7;
    private javax.swing.JTextField txtM3RV8;
    private javax.swing.JTextField txtM3RV9;
    private javax.swing.JTextField txtM3V1;
    // End of variables declaration//GEN-END:variables

   
}
